simulation_period: 60.0
communication_range: 8.0

setting_list:
  - simD0S0_3
  - simD0S0_4
  - simD0S0_5
  - simD0S0_6
  - simD0S0_7
  - simD0S0_8
  - simD0S0_9
  - simD0S1_0
  - simD0S1_1
  - simD0S1_2
  - simD0S1_3
  - simD0S1_4
  - simD0S1_5
  - simD3S0_3
  - simD3S0_4
  - simD3S0_5
  - simD3S0_6
  - simD3S0_7
  - simD3S0_8
  - simD3S0_9
  - simD3S1_0
  - simD3S1_1
  - simD3S1_2
  - simD3S1_3
  - simD3S1_4
  - simD3S1_5
  - simD7S0_3
  - simD7S0_4
  - simD7S0_5
  - simD7S0_6
  - simD7S0_7
  - simD7S0_8
  - simD7S0_9
  - simD7S1_0
  - simD7S1_1
  - simD7S1_2
  - simD7S1_3
  - simD7S1_4
  - simD7S1_5
  - simD9S0_3
  - simD9S0_4
  - simD9S0_5
  - simD9S0_6
  - simD9S0_7
  - simD9S0_8
  - simD9S0_9
  - simD9S1_0
  - simD9S1_1
  - simD9S1_2
  - simD9S1_3
  - simD9S1_4
  - simD9S1_5

simD0S0_3:
  delay_time: 0
  robot_speed: 0.3

simD0S0_4:
  delay_time: 0
  robot_speed: 0.4

simD0S0_5:
  delay_time: 0
  robot_speed: 0.5

simD0S0_6:
  delay_time: 0
  robot_speed: 0.6

simD0S0_7:
  delay_time: 0
  robot_speed: 0.7

simD0S0_8:
  delay_time: 0
  robot_speed: 0.8

simD0S0_9:
  delay_time: 0
  robot_speed: 0.9

simD0S1_0:
  delay_time: 0
  robot_speed: 1.0

simD0S1_1:
  delay_time: 0
  robot_speed: 1.1

simD0S1_2:
  delay_time: 0
  robot_speed: 1.2

simD0S1_3:
  delay_time: 0
  robot_speed: 1.3

simD0S1_4:
  delay_time: 0
  robot_speed: 1.4

simD0S1_5:
  delay_time: 0
  robot_speed: 1.5

simD3S0_3:
  delay_time: 3
  robot_speed: 0.3

simD3S0_4:
  delay_time: 3
  robot_speed: 0.4

simD3S0_5:
  delay_time: 3
  robot_speed: 0.5

simD3S0_6:
  delay_time: 3
  robot_speed: 0.6

simD3S0_7:
  delay_time: 3
  robot_speed: 0.7

simD3S0_8:
  delay_time: 3
  robot_speed: 0.8

simD3S0_9:
  delay_time: 3
  robot_speed: 0.9

simD3S1_0:
  delay_time: 3
  robot_speed: 1.0

simD3S1_1:
  delay_time: 3
  robot_speed: 1.1

simD3S1_2:
  delay_time: 3
  robot_speed: 1.2

simD3S1_3:
  delay_time: 3
  robot_speed: 1.3

simD3S1_4:
  delay_time: 3
  robot_speed: 1.4

simD3S1_5:
  delay_time: 3
  robot_speed: 1.5

simD5S0_3:
  delay_time: 5
  robot_speed: 0.3

simD5S0_4:
  delay_time: 5
  robot_speed: 0.4

simD5S0_5:
  delay_time: 5
  robot_speed: 0.5

simD5S0_6:
  delay_time: 5
  robot_speed: 0.6

simD5S0_7:
  delay_time: 5
  robot_speed: 0.7

simD5S0_8:
  delay_time: 5
  robot_speed: 0.8

simD5S0_9:
  delay_time: 5
  robot_speed: 0.9

simD5S1_0:
  delay_time: 5
  robot_speed: 1.0

simD5S1_1:
  delay_time: 5
  robot_speed: 1.1

simD5S1_2:
  delay_time: 5
  robot_speed: 1.2

simD5S1_3:
  delay_time: 5
  robot_speed: 1.3

simD5S1_4:
  delay_time: 5
  robot_speed: 1.4

simD5S1_5:
  delay_time: 5
  robot_speed: 1.5

simD7S0_3:
  delay_time: 7
  robot_speed: 0.3

simD7S0_4:
  delay_time: 7
  robot_speed: 0.4

simD7S0_5:
  delay_time: 7
  robot_speed: 0.5

simD7S0_6:
  delay_time: 7
  robot_speed: 0.6

simD7S0_7:
  delay_time: 7
  robot_speed: 0.7

simD7S0_8:
  delay_time: 7
  robot_speed: 0.8

simD7S0_9:
  delay_time: 7
  robot_speed: 0.9

simD7S1_0:
  delay_time: 7
  robot_speed: 1.0

simD7S1_1:
  delay_time: 7
  robot_speed: 1.1

simD7S1_2:
  delay_time: 7
  robot_speed: 1.2

simD7S1_3:
  delay_time: 7
  robot_speed: 1.3

simD7S1_4:
  delay_time: 7
  robot_speed: 1.4

simD7S1_5:
  delay_time: 7
  robot_speed: 1.5

simD9S0_3:
  delay_time: 9
  robot_speed: 0.3

simD9S0_4:
  delay_time: 9
  robot_speed: 0.4

simD9S0_5:
  delay_time: 9
  robot_speed: 0.5

simD9S0_6:
  delay_time: 9
  robot_speed: 0.6

simD9S0_7:
  delay_time: 9
  robot_speed: 0.7

simD9S0_8:
  delay_time: 9
  robot_speed: 0.8

simD9S0_9:
  delay_time: 9
  robot_speed: 0.9

simD9S1_0:
  delay_time: 9
  robot_speed: 1.0

simD9S1_1:
  delay_time: 9
  robot_speed: 1.1

simD9S1_2:
  delay_time: 9
  robot_speed: 1.2

simD9S1_3:
  delay_time: 9
  robot_speed: 1.3

simD9S1_4:
  delay_time: 9
  robot_speed: 1.4

simD9S1_5:
  delay_time: 9
  robot_speed: 1.5
